// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbsnleznifhfoudaxxlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZic25sZXpuaWZoZm91ZGF4eGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mzg4ODEsImV4cCI6MjA2MjIxNDg4MX0.ZdsjVnO5JNzs-jF6VPaX0djDubaU5CHk9JbJvtLwRSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);